spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5333/bot_builder
    username: ingins
    password: secret
  liquibase:
    default-schema: public
    change-log: "classpath:/db/changelog/changelog-master.yml"
    parameters:
      schema: bot_builder
      catalog: bot_builder
    liquibase-schema: public
  application:
    name: bot_builder
  jpa:
    properties:
      hibernate:
        default_schema: bot_builder
        order_inserts: true
        order_updates: true
        format_sql: true
        jdbc:
          batch_size: 100
          fetch_size: 100
          batch_versioned_data: true
    open-in-view: false
    generate-ddl: false
server:
  port: 8888
